Password checker game
JaegerCryptic/CyberLab pull request #4
Opened 2024-09-24 07:04 UTC by MihailStam

Added Password Checker Game to be compatible with tsx

2024-09-24 07:25 UTC, Ganoush69 commented on password-checker-game/public/index.html
@JaegerCryptic  is this meant to be here?

2024-09-24 07:28 UTC, MihailStam commented on password-checker-game/public/index.html
oh what, that was meant to be deleted

2024-09-24 08:02 UTC, JaegerCryptic requested changes

2024-09-24 08:02 UTC, JaegerCryptic commented on src/main.tsx
No changes should be in main. Main is the head of the website that directs everywhere and provides the structure we want.

Also, make sure your linting is working and that you have a formatter selected. You should be formatting with Prettier and have settings enabled to format on save. https://stackoverflow.com/questions/39494277/how-do-you-format-code-on-save-in-vs-code

2024-09-24 08:02 UTC, JaegerCryptic commented on src/components/RuleList.tsx
> +const RuleList: React.FC<RuleListProps> = ({ rules }) => {
```suggestion
export const RuleList = (props: RuleListProps)  => {
  const { rules } = props
```
This is easier to read and shorter

2024-09-24 08:02 UTC, JaegerCryptic commented on src/components/RuleList.tsx
> +export default RuleList;
```suggestion
```

2024-09-24 08:02 UTC, JaegerCryptic commented on src/main.tsx
> +);
Change your prettier settings so it doesn't add semicolons onto the end of everything

2024-09-24 08:02 UTC, JaegerCryptic commented on src/components/PasswordChecker/PasswordChecker.tsx
We don't have a folder called components. We have a folder for common components if the component is used repeatedly in different situations, but this is pretty linear.. This would go into a folder like such: src/features/passwordChecker/components

2024-09-24 08:02 UTC, JaegerCryptic commented on src/components/PasswordChecker/StrengthIndicator.tsx
> +const StrengthIndicator: React.FC<StrengthIndicatorProps> = ({ strength }) => {
```suggestion
const StrengthIndicator = (props: StrengthIndicatorProps) => {
 const { strength} = props
```

2024-09-24 08:02 UTC, JaegerCryptic commented on src/components/PasswordChecker/StrengthIndicator.tsx
> +      style={{ color: '#4a4a4a', marginTop: '1rem' }}  // Darker gray text
Don't use style here. MUI components have a prop called sx which does the same thing with better support. style will not work most of the time. Also all colours can be found in style.ts. see how that is used and use it here

2024-09-24 08:02 UTC, JaegerCryptic commented on src/components/PasswordChecker/StrengthIndicator.tsx
> +  strength: string;
Will strength always be a string or could it be null?

2024-09-24 08:02 UTC, JaegerCryptic commented on src/components/PasswordChecker/PasswordInput.tsx
> +const PasswordInput: React.FC<PasswordInputProps> = ({ password, setPassword }) => {
```suggestion
export const PasswordInput = (props: PasswordInputProps) => {
	const { password, setPassword } = props
```

2024-09-24 08:02 UTC, JaegerCryptic commented on src/components/PasswordChecker/PasswordInput.tsx
> +export default PasswordInput;
```suggestion
```

2024-09-24 08:02 UTC, JaegerCryptic commented on src/components/PasswordChecker/PasswordChecker.tsx
> +          color="black"  // Black text
```suggestion
           sx={{ color: 'black' }}
```

2024-09-24 08:02 UTC, JaegerCryptic commented on src/components/PasswordChecker/PasswordChecker.tsx
> +export default PasswordChecker;
```suggestion
```

2024-09-24 08:02 UTC, JaegerCryptic commented on src/components/PasswordChecker/PasswordChecker.tsx
> +const PasswordChecker: React.FC = () => {
```suggestion
export const PasswordChecker = () => {
```

2024-09-24 08:02 UTC, JaegerCryptic commented on src/components/PasswordChecker/PasswordChecker.tsx
> +    }
Optimise the function to avoid recalculating the same values multiple times.

2024-09-24 08:02 UTC, JaegerCryptic commented on src/components/PasswordChecker/PasswordChecker.tsx
> +  };
break this up into smaller helper functions

2024-09-24 08:02 UTC, JaegerCryptic commented on src/components/PasswordChecker/PasswordChecker.tsx
> +    ];
This never changes. It can be stored as a constant in a new folder like so: src/features/passwordChecker/constants

2024-09-24 08:02 UTC, JaegerCryptic commented on src/components/PasswordChecker/PasswordChecker.tsx
> +
```suggestion
	const getCharacterSetSize = (password: string): number => {
		let size = 0
		if (/[a-z]/.test(password)) size += 26
		if (/[A-Z]/.test(password)) size += 26
		if (/\d/.test(password)) size += 10
		if (/[\W_]/.test(password)) size += 32
		return size
	}
```
This can be changed to a helper function and put into a helper folder like so, src/features/passwordChecker/helpers.ts

2024-09-24 08:02 UTC, JaegerCryptic commented on src/components/PasswordChecker/PasswordChecker.tsx
> +    const guessesPerSecond = 1e9;
Same with calculateStrength
`

    const calculateStrength = (password: string): void => {
		if (password.length === 0) {
			setTimeToCrack("0 seconds")
			setBgColor("blue")
			return
		}

		const length = password.length
		const characterSetSize = getCharacterSetSize(password)

		const guessesPerSecond = 1e9
		const totalGuesses = Math.pow(characterSetSize, length)
		let timeToCrackInSeconds = totalGuesses / guessesPerSecond

		if (!isFinite(timeToCrackInSeconds)) {
			setTimeToCrack("Infinity")
			setBgColor("black")
			return
		}

		let selectedUnit = "seconds"
		let timeValue = timeToCrackInSeconds

		for (let i = 0; i < timeUnits.length; i++) {
			if (timeToCrackInSeconds < timeUnits[i].value) break
			selectedUnit = timeUnits[i].unit
			timeValue = timeToCrackInSeconds / timeUnits[i].value
		}

		if (
			(selectedUnit === "weeks" && timeValue >= 1) ||
			selectedUnit.includes("months") ||
			selectedUnit.includes("years")
		) {
			setBgColor("green")
		} else {
			setBgColor("red")
		}

		setTimeToCrack(`${timeValue.toFixed(2)} ${selectedUnit}`)
	}
`

2024-10-07 04:43 UTC, closed without merging

2024-10-07 04:43 UTC, JaegerCryptic commented
Added to main indirectly through another branch